# This is a basic workflow to help you get started with Actions

name: make

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  linux-build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: Increment version
        uses: reecetech/version-increment@2023.4.1
        id: version
        with:
          scheme: semver
          increment: patch

      - name: Build
        run: |
            echo "char *version = \"${{ steps.version.outputs.version }}\";" > headers/version.h && make && ls -R
            zip "SHA1check-linux.zip" SHA1check

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "SHA1check-linux.zip"
          replacesArtifacts: false
          allowUpdates: true
          generateReleaseNotes: true
          name: "Release v${{ steps.version.outputs.version }}"
          tag: "v${{ steps.version.outputs.version }}"

          #  windows-build:
          #    # The type of runner that the job will run on
          #    runs-on: windows-2022
          #
          #    defaults:
          #      run:
          #        shell: bash
          #
          #    # Steps represent a sequence of tasks that will be executed as part of the job
          #    steps:
          #      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
          #      - name: Checkout
          #        uses: actions/checkout@v3
          #
          #      - name: Increment version
          #        uses: reecetech/version-increment@2023.4.1
          #        id: version
          #        with:
          #          scheme: semver
          #          increment: minor
          #
          #      - name: Build
          #        run: echo "char *version = \"${{ steps.version.outputs.version }}\";" > headers/version.h && make && ls
          #
          #      - name: Create Release
          #        uses: ncipollo/release-action@v1
          #        with:
          #          artifacts: "SHA1check.exe"
          #          replacesArtifacts: false
          #          allowUpdates: true
          #          generateReleaseNotes: true
          #          name: "Release v${{ steps.version.outputs.version }}"
          #          tag: "v${{ steps.version.outputs.version }}"
